version: '3'
services:
 object_detection:
  runtime: nvidia
  image: datascience
  container_name: datascience
  restart: always
  environment:
   - TERM=xterm
  hostname: '127.0.0.1'
  ports:
   - "8888:8888"
